#!/bin/bash

# change to this directory
# cd "$(dirname "${BASH_SOURCE[0]}")" || exit

"$(dirname "${BASH_SOURCE[0]}")/create"
"$(dirname "${BASH_SOURCE[0]}")/deploy"
"$(dirname "${BASH_SOURCE[0]}")/jumpbox"
