#!/bin/bash

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

docker build /workspaces/ngsa-app -t k3d-registry.localhost:5500/ngsa-app:local
docker push k3d-registry.localhost:5500/ngsa-app:local
kubectl delete -f deploy/webv --ignore-not-found=true
kubectl delete -f deploy/ngsa-memory --ignore-not-found=true
kubectl apply -f deploy/ngsa-local
kubectl wait pod ngsa-memory --for condition=ready --timeout=30s
kubectl apply -f deploy/webv
kubectl wait pod webv --for condition=ready --timeout=30s
kubectl get po
http localhost:30080/version