#!/bin/bash

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

kubectl delete ns ngsa
kubectl delete pod jumpbox --ignore-not-found=true
kubectl delete ns monitoring --ignore-not-found=true
kubectl delete ns logging --ignore-not-found=true
