#!/bin/bash

# name: gitops
# short: Run GitOps in the current directory

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

docker run -it --rm -v "$PWD":/ago ghcr.io/retaildevcrews/autogitops:beta -r "$AKDC_REPO" -p "$AKDC_PAT"
