apiVersion: v1
kind: Pod
metadata:
  name: ai-order-accuracy
  namespace: ai-order-accuracy
  labels:
    app: ai-order-accuracy

spec:
  containers:
  - name: ds
    imagePullPolicy: Always
    image: k3d-registry.localhost:5500/aioa:local
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    args:
      - --in-memory
      - --prometheus
      - --log-level
      - Warning
      - --request-log-level
      - Information
      - --zone
      - dev
      - --region
      - dev
    ports:
    - containerPort: 8080
    readinessProbe:
      initialDelaySeconds: 5
      httpGet:
        path: /version
        port: 8080
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 300
      httpGet:
        path: /healthz
        port: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: ai-order-accuracy
  namespace: ai-order-accuracy
  labels:
    app: ai-order-accuracy
spec:
  type: NodePort
  selector:
    app: ai-order-accuracy
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
