#!/bin/bash


function akdc_usage() {
    echo "Usage: akdc"
    echo "    check   -- check status on each server"
    echo "    delete  -- delete an Azure Resource Group and associated Azure DNS record"
    echo "    exec    -- execute a bash command on each server"
    echo "    flux    -- flux commands"
    echo "    groups  -- show Azure groups"
    echo "    ssh     -- ssh into a cluster by server name"
}

# execute a bash command on all IPs
function akdc_exec() {
    # shellcheck disable=2002,SC2013

    for line in $(cat ips | sort | cut -f2);
    do
        ssh -p 2222 -o "StrictHostKeyChecking=no" -o ConnectTimeout=5 akdc@"$line" "$@"
    done
}

# execute a bash command on all IPs in background
function akdc_exec_task() {
    # shellcheck disable=2002,SC2013

    for line in $(cat ips | sort | cut -f2);
    do
        ssh -p 2222 -o "StrictHostKeyChecking=no" -o ConnectTimeout=5 akdc@"$line" "$@" &
    done
}

# run ssh using the ips file
function akdc_ssh() {
    # shellcheck disable=2002,SC2013
    ssh -p 2222 -o "StrictHostKeyChecking=no" akdc@"$(cat ips | grep "$1" | tail -1 | cut -f 2)"
}

### main akdc function
if [ $# == 0 ]
then
    akdc_usage
    exit 0
fi

# shellcheck disable=2002,2016
case $1 in
    check)
        case $2 in
            dapr)
                akdc_exec_task 'if [[ $(kubectl get ns) == *"dapr-system"* ]]; then echo "$(hostname) success"; else echo "$(hostname) failed"; fi'
                ;;
            flux)
                akdc_exec_task 'if [[ $(kubectl get ns) == *"flux-check"* ]]; then echo "$(hostname) success"; else echo "$(hostname) failed"; fi'
                ;;
            ngsa)
                akdc_exec_task 'if [[ $(kubectl get pods -A) == *"ngsa"* ]]; then echo "$(hostname) found"; else echo "$(hostname) not found"; fi'
                ;;
            retries)
                akdc_exec_task 'echo "$(hostname) $(cat status | grep -e retries | tail -1)"'
                ;;
            radius)
                akdc_exec_task 'if [[ $(kubectl get ns) == *"radius-system"* ]]; then echo "$(hostname) success"; else echo "$(hostname) failed"; fi'
                ;;
            setup)
                akdc_exec_task 'echo "$(hostname) $(cat status | tail -1)"'
                ;;
            ssl)
                akdc_exec_task 'echo "$(hostname) $(curl -s https://$(hostname).cseretail.com/tinybench/17)"'
                ;;
            *)
                echo "Usage: akdc check command"
                echo "    dapr     -- check dapr status on each server"
                echo "    flux     -- check flux status on each server"
                echo "    ngsa     -- check ngsa status on each server"
                echo "    radius   -- check radius status on each server"
                echo "    setup    -- check setup status on each server"
                echo "    ssl      -- curl tinybench via https on each server"
                ;;
        esac
        ;;
    exec)
        akdc_exec "$2"
        ;;
    flux)
        case $2 in
            setup)
                akdc_exec_task 'if [[ $(kubectl get ns) == *"flux-check"* ]]; then echo "$(hostname) success"; else echo "$(hostname) failed" && ./flux-setup.sh; fi'
                ;;

            reconcile)
                akdc_exec_task flux reconcile source git gitops
                ;;

            *)
                echo "Usage: akdc $1 command"
                echo "Commands"
                echo "   setup      -- run flux reconcile on each server"
                echo "   reconcile  -- setup flux on each server if needed"
                ;;
        esac
        ;;

    groups)
        az group list -o table | sort | grep -e central- -e east- -e west-
        ;;

    ssh)
        if [ $# != 2 ]
        then
            echo "Usage: akdc $1 ServerName"
            echo "Valid servers"
            cat ips | sort | cut -f1
            exit 1
        fi

        akdc_ssh "$2"
        ;;
    delete)
        if [ $# != 2 ]; then
            echo "Usage: akdc $1 ServerName"
            echo "Valid servers"
            cat ips | sort | cut -f1
            exit 1
        fi

        serverName=$2
        response=$(az group list --query "[?tags.server == '$serverName']" -o json)
        resourceGroupName=$(echo "$response" | jq -r '.[].name')
        zone=$(echo "$response" | jq -r '.[].tags.zone')

        echo "Deleting Resource Group: $resourceGroupName"
        az group delete -n "$resourceGroupName" --yes --no-wait

        if [ "$zone" != "null" ]; then
            echo "Deleting Record: $resourceGroupName in Zone:$zone"
            az network dns record-set a delete -g tld -z "$zone" --yes -n "$resourceGroupName"
        fi
        ;;
    *)
        akdc_usage
        ;;
esac
