#!/bin/bash

cd ..

./create-cluster.sh central tx austin 101 centralus &
./create-cluster.sh central tx austin 102 centralus &
./create-cluster.sh central tx austin 103 centralus &
./create-cluster.sh central tx austin 104 centralus &
./create-cluster.sh central tx austin 105 centralus &
./create-cluster.sh central tx dallas 101 centralus &
./create-cluster.sh central tx dallas 102 centralus &
./create-cluster.sh central tx dallas 103 centralus &
./create-cluster.sh central tx dallas 104 centralus &
./create-cluster.sh central tx dallas 105 centralus &
./create-cluster.sh central tx east 101 centralus &
./create-cluster.sh central tx east 102 centralus &
./create-cluster.sh central tx east 103 centralus &
./create-cluster.sh central tx east 104 centralus &
./create-cluster.sh central tx east 105 centralus &
./create-cluster.sh central tx houston 101 centralus &
./create-cluster.sh central tx houston 102 centralus &
./create-cluster.sh central tx houston 103 centralus &
./create-cluster.sh central tx houston 104 centralus &
./create-cluster.sh central tx houston 105 centralus &
./create-cluster.sh central tx north 101 centralus &
./create-cluster.sh central tx north 102 centralus &
./create-cluster.sh central tx north 103 centralus &
./create-cluster.sh central tx north 104 centralus &
./create-cluster.sh central tx north 105 centralus &
./create-cluster.sh central tx san 101 centralus &
./create-cluster.sh central tx san 102 centralus &
./create-cluster.sh central tx san 103 centralus &
./create-cluster.sh central tx san 104 centralus &
./create-cluster.sh central tx san 105 centralus &
./create-cluster.sh central tx south 101 centralus &
./create-cluster.sh central tx south 102 centralus &
./create-cluster.sh central tx south 103 centralus &
./create-cluster.sh central tx south 104 centralus &
./create-cluster.sh central tx south 105 centralus &
./create-cluster.sh central tx west 101 centralus &
./create-cluster.sh central tx west 102 centralus &
./create-cluster.sh central tx west 103 centralus &
./create-cluster.sh central tx west 104 centralus &
./create-cluster.sh central tx west 105 centralus &
./create-cluster.sh central mo columbia 101 centralus &
./create-cluster.sh central mo columbia 102 centralus &
./create-cluster.sh central mo columbia 103 centralus &
./create-cluster.sh central mo columbia 104 centralus &
./create-cluster.sh central mo columbia 105 centralus &
./create-cluster.sh central mo east 101 centralus &
./create-cluster.sh central mo east 102 centralus &
./create-cluster.sh central mo east 103 centralus &
./create-cluster.sh central mo east 104 centralus &
./create-cluster.sh central mo east 105 centralus &
./create-cluster.sh central mo kc 101 centralus &
./create-cluster.sh central mo kc 102 centralus &
./create-cluster.sh central mo kc 103 centralus &
./create-cluster.sh central mo kc 104 centralus &
./create-cluster.sh central mo kc 105 centralus &
./create-cluster.sh central mo north 101 centralus &
./create-cluster.sh central mo north 102 centralus &
./create-cluster.sh central mo north 103 centralus &
./create-cluster.sh central mo north 104 centralus &
./create-cluster.sh central mo north 105 centralus &
./create-cluster.sh central mo south 101 centralus &
./create-cluster.sh central mo south 102 centralus &
./create-cluster.sh central mo south 103 centralus &
./create-cluster.sh central mo south 104 centralus &
./create-cluster.sh central mo south 105 centralus &
./create-cluster.sh central mo stlouis 101 centralus &
./create-cluster.sh central mo stlouis 102 centralus &
./create-cluster.sh central mo stlouis 103 centralus &
./create-cluster.sh central mo stlouis 104 centralus &
./create-cluster.sh central mo stlouis 105 centralus &
./create-cluster.sh central mo west 101 centralus &
./create-cluster.sh central mo west 102 centralus &
./create-cluster.sh central mo west 103 centralus &
./create-cluster.sh central mo west 104 centralus &
./create-cluster.sh central mo west 105 centralus &
./create-cluster.sh east nc charlotte 101 eastus &
./create-cluster.sh east nc charlotte 102 eastus &
./create-cluster.sh east nc charlotte 103 eastus &
./create-cluster.sh east nc charlotte 104 eastus &
./create-cluster.sh east nc charlotte 105 eastus &
./create-cluster.sh east nc durham 101 eastus &
./create-cluster.sh east nc durham 102 eastus &
./create-cluster.sh east nc durham 103 eastus &
./create-cluster.sh east nc durham 104 eastus &
./create-cluster.sh east nc durham 105 eastus &
./create-cluster.sh east nc east 101 eastus &
./create-cluster.sh east nc east 102 eastus &
./create-cluster.sh east nc east 103 eastus &
./create-cluster.sh east nc east 104 eastus &
./create-cluster.sh east nc east 105 eastus &
./create-cluster.sh east nc raleigh 101 eastus &
./create-cluster.sh east nc raleigh 102 eastus &
./create-cluster.sh east nc raleigh 103 eastus &
./create-cluster.sh east nc raleigh 104 eastus &
./create-cluster.sh east nc raleigh 105 eastus &
./create-cluster.sh east nc west 101 eastus &
./create-cluster.sh east nc west 102 eastus &
./create-cluster.sh east nc west 103 eastus &
./create-cluster.sh east nc west 104 eastus &
./create-cluster.sh east nc west 105 eastus &
