#!/bin/bash

cd ..

./create-cluster.sh west ca la 101 westus &
./create-cluster.sh west ca la 102 westus &
./create-cluster.sh west ca la 103 westus &
./create-cluster.sh west ca la 104 westus &
./create-cluster.sh west ca la 105 westus &
./create-cluster.sh west ca north 101 westus &
./create-cluster.sh west ca north 102 westus &
./create-cluster.sh west ca north 103 westus &
./create-cluster.sh west ca north 104 westus &
./create-cluster.sh west ca north 105 westus &
./create-cluster.sh west ca sac 101 westus &
./create-cluster.sh west ca sac 102 westus &
./create-cluster.sh west ca sac 103 westus &
./create-cluster.sh west ca sac 104 westus &
./create-cluster.sh west ca sac 105 westus &
./create-cluster.sh west ca sfo 101 westus &
./create-cluster.sh west ca sfo 102 westus &
./create-cluster.sh west ca sfo 103 westus &
./create-cluster.sh west ca sfo 104 westus &
./create-cluster.sh west ca sfo 105 westus &
./create-cluster.sh west ca sd 101 westus &
./create-cluster.sh west ca sd 102 westus &
./create-cluster.sh west ca sd 103 westus &
./create-cluster.sh west ca sd 104 westus &
./create-cluster.sh west ca sd 105 westus &
./create-cluster.sh west ca south 101 westus &
./create-cluster.sh west ca south 102 westus &
./create-cluster.sh west ca south 103 westus &
./create-cluster.sh west ca south 104 westus &
./create-cluster.sh west ca south 105 westus &
./create-cluster.sh west ca west 101 westus &
./create-cluster.sh west ca west 102 westus &
./create-cluster.sh west ca west 103 westus &
./create-cluster.sh west ca west 104 westus &
./create-cluster.sh west ca west 105 westus &
./create-cluster.sh west wa east 101 westus &
./create-cluster.sh west wa east 102 westus &
./create-cluster.sh west wa east 103 westus &
./create-cluster.sh west wa east 104 westus &
./create-cluster.sh west wa east 105 westus &
./create-cluster.sh west wa central 101 westus &
./create-cluster.sh west wa central 102 westus &
./create-cluster.sh west wa central 103 westus &
./create-cluster.sh west wa central 104 westus &
./create-cluster.sh west wa central 105 westus &
./create-cluster.sh west wa olympia 101 westus &
./create-cluster.sh west wa olympia 102 westus &
./create-cluster.sh west wa olympia 103 westus &
./create-cluster.sh west wa olympia 104 westus &
./create-cluster.sh west wa olympia 105 westus &
./create-cluster.sh west wa seattle 101 westus &
./create-cluster.sh west wa seattle 102 westus &
./create-cluster.sh west wa seattle 103 westus &
./create-cluster.sh west wa seattle 104 westus &
./create-cluster.sh west wa seattle 105 westus &
./create-cluster.sh west wa spokane 101 westus &
./create-cluster.sh west wa spokane 102 westus &
./create-cluster.sh west wa spokane 103 westus &
./create-cluster.sh west wa spokane 104 westus &
./create-cluster.sh west wa spokane 105 westus &
./create-cluster.sh west wa west 101 westus &
./create-cluster.sh west wa west 102 westus &
./create-cluster.sh west wa west 103 westus &
./create-cluster.sh west wa west 104 westus &
./create-cluster.sh west wa west 105 westus &
./create-cluster.sh east ga athens 101 eastus &
./create-cluster.sh east ga athens 102 eastus &
./create-cluster.sh east ga athens 103 eastus &
./create-cluster.sh east ga athens 104 eastus &
./create-cluster.sh east ga athens 105 eastus &
./create-cluster.sh east ga atlanta 101 eastus &
./create-cluster.sh east ga atlanta 102 eastus &
./create-cluster.sh east ga atlanta 103 eastus &
./create-cluster.sh east ga atlanta 104 eastus &
./create-cluster.sh east ga atlanta 105 eastus &
./create-cluster.sh east ga north 101 eastus &
./create-cluster.sh east ga north 102 eastus &
./create-cluster.sh east ga north 103 eastus &
./create-cluster.sh east ga north 104 eastus &
./create-cluster.sh east ga north 105 eastus &
./create-cluster.sh east ga south 101 eastus &
./create-cluster.sh east ga south 102 eastus &
./create-cluster.sh east ga south 103 eastus &
./create-cluster.sh east ga south 104 eastus &
./create-cluster.sh east ga south 105 eastus &
