#!/bin/bash

# name: delete
# short: delete a DNS entry

if ! az account show -o table > /dev/null
then
    echo "Please login to Azure"
    exit 0
fi

if [ "$AKDC_DNS_RG" = "" ]
then
    echo "Please export AKDC_DNS_RG"
    exit 0
fi

if [ "$AKDC_SSL" = "" ]
then
    echo "Please export AKDC_SSL"
    exit 0
fi

set -e

host=$1

if [ "$host" = "" ]
then
    echo "Usage: flt dns delete hostName"
    exit 0
fi

if ! az account show -o table > /dev/null
then
    echo "Please login to Azure"
    exit 0
fi

# delete the old DNS entry
az network dns record-set a delete \
-y \
-o table \
-g "$AKDC_DNS_RG" \
-z "$AKDC_SSL" \
-n "$host"
