#!/bin/bash

# name: list
# short: List DNS entries

if ! az account show -o table > /dev/null
then
    echo "Please login to Azure"
    exit 0
fi

if [ "$AKDC_DNS_RG" = "" ]
then
    echo "Please export AKDC_DNS_RG"
    exit 0
fi

if [ "$AKDC_SSL" = "" ]
then
    echo "Please export AKDC_SSL"
    exit 0
fi

az network dns record-set a list -g "$AKDC_DNS_RG" -z "$AKDC_SSL" --query '[].fqdn' -o tsv | sort
