#!/bin/bash

# change to this directory
cd "$(dirname "${BASH_SOURCE[0]}")" || exit

create-cluster -c east-nc-charlotte-101 -q -l eastus &
create-cluster -c east-nc-charlotte-102 -q -l eastus &
create-cluster -c east-nc-charlotte-103 -q -l eastus &
create-cluster -c east-nc-charlotte-104 -q -l eastus &
create-cluster -c east-nc-charlotte-105 -q -l eastus &
create-cluster -c east-nc-durham-101 -q -l eastus &
create-cluster -c east-nc-durham-102 -q -l eastus &
create-cluster -c east-nc-durham-103 -q -l eastus &
create-cluster -c east-nc-durham-104 -q -l eastus &
create-cluster -c east-nc-durham-105 -q -l eastus &
create-cluster -c east-nc-east-101 -q -l eastus &
create-cluster -c east-nc-east-102 -q -l eastus &
create-cluster -c east-nc-east-103 -q -l eastus &
create-cluster -c east-nc-east-104 -q -l eastus &
create-cluster -c east-nc-east-105 -q -l eastus &
create-cluster -c east-nc-raleigh-101 -q -l eastus &
create-cluster -c east-nc-raleigh-102 -q -l eastus &
create-cluster -c east-nc-raleigh-103 -q -l eastus &
create-cluster -c east-nc-raleigh-104 -q -l eastus &
create-cluster -c east-nc-raleigh-105 -q -l eastus &
create-cluster -c east-nc-west-101 -q -l eastus &
create-cluster -c east-nc-west-102 -q -l eastus &
create-cluster -c east-nc-west-103 -q -l eastus &
create-cluster -c east-nc-west-104 -q -l eastus &
create-cluster -c east-nc-west-105 -q -l eastus &
create-cluster -c west-ca-la-101 -q -l westus &
create-cluster -c west-ca-la-102 -q -l westus &
create-cluster -c west-ca-la-103 -q -l westus &
create-cluster -c west-ca-la-104 -q -l westus &
create-cluster -c west-ca-la-105 -q -l westus &
create-cluster -c west-ca-north-101 -q -l westus &
create-cluster -c west-ca-north-102 -q -l westus &
create-cluster -c west-ca-north-103 -q -l westus &
create-cluster -c west-ca-north-104 -q -l westus &
create-cluster -c west-ca-north-105 -q -l westus &
create-cluster -c west-ca-sac-101 -q -l westus &
create-cluster -c west-ca-sac-102 -q -l westus &
create-cluster -c west-ca-sac-103 -q -l westus &
create-cluster -c west-ca-sac-104 -q -l westus &
create-cluster -c west-ca-sac-105 -q -l westus &
create-cluster -c west-ca-sand-101 -q -l westus &
create-cluster -c west-ca-sand-102 -q -l westus &
create-cluster -c west-ca-sand-103 -q -l westus &
create-cluster -c west-ca-sand-104 -q -l westus &
create-cluster -c west-ca-sand-105 -q -l westus &
create-cluster -c west-ca-sfo-101 -q -l westus &
create-cluster -c west-ca-sfo-102 -q -l westus &
create-cluster -c west-ca-sfo-103 -q -l westus &
create-cluster -c west-ca-sfo-104 -q -l westus &
create-cluster -c west-ca-sfo-105 -q -l westus &
create-cluster -c west-ca-south-101 -q -l westus &
create-cluster -c west-ca-south-102 -q -l westus &
create-cluster -c west-ca-south-103 -q -l westus &
create-cluster -c west-ca-south-104 -q -l westus &
create-cluster -c west-ca-south-105 -q -l westus &
create-cluster -c west-ca-west-101 -q -l westus &
create-cluster -c west-ca-west-102 -q -l westus &
create-cluster -c west-ca-west-103 -q -l westus &
create-cluster -c west-ca-west-104 -q -l westus &
create-cluster -c west-ca-west-105 -q -l westus &
create-cluster -c west-wc-central-101 -q -l westus &
create-cluster -c west-wc-central-102 -q -l westus &
create-cluster -c west-wc-central-103 -q -l westus &
create-cluster -c west-wc-central-104 -q -l westus &
create-cluster -c west-wc-central-105 -q -l westus &
create-cluster -c west-wc-east-101 -q -l westus &
create-cluster -c west-wc-east-102 -q -l westus &
create-cluster -c west-wc-east-103 -q -l westus &
create-cluster -c west-wc-east-104 -q -l westus &
create-cluster -c west-wc-east-105 -q -l westus &
create-cluster -c west-wc-olympia-101 -q -l westus &
create-cluster -c west-wc-olympia-102 -q -l westus &
create-cluster -c west-wc-olympia-103 -q -l westus &
create-cluster -c west-wc-olympia-104 -q -l westus &
create-cluster -c west-wc-olympia-105 -q -l westus &
create-cluster -c west-wc-sea-101 -q -l westus &
create-cluster -c west-wc-sea-102 -q -l westus &
create-cluster -c west-wc-sea-103 -q -l westus &
create-cluster -c west-wc-sea-104 -q -l westus &
create-cluster -c west-wc-sea-105 -q -l westus &
create-cluster -c west-wc-spokane-101 -q -l westus &
create-cluster -c west-wc-spokane-102 -q -l westus &
create-cluster -c west-wc-spokane-103 -q -l westus &
create-cluster -c west-wc-spokane-104 -q -l westus &
create-cluster -c west-wc-spokane-105 -q -l westus &
create-cluster -c west-wc-tacoma-101 -q -l westus &
create-cluster -c west-wc-tacoma-102 -q -l westus &
create-cluster -c west-wc-tacoma-103 -q -l westus &
create-cluster -c west-wc-tacoma-104 -q -l westus &
create-cluster -c west-wc-tacoma-105 -q -l westus &
create-cluster -c west-wc-west-101 -q -l westus &
create-cluster -c west-wc-west-102 -q -l westus &
create-cluster -c west-wc-west-103 -q -l westus &
create-cluster -c west-wc-west-104 -q -l westus &
create-cluster -c west-wc-west-105 -q -l westus &
