#!/bin/bash

# change to this directory
cd "$(dirname "${BASH_SOURCE[0]}")" || exit

create-cluster east nc charlotte 101 -l eastus &
create-cluster east nc charlotte 102 -l eastus &
create-cluster east nc charlotte 103 -l eastus &
create-cluster east nc charlotte 104 -l eastus &
create-cluster east nc charlotte 105 -l eastus &
create-cluster east nc durham 101 -l eastus &
create-cluster east nc durham 102 -l eastus &
create-cluster east nc durham 103 -l eastus &
create-cluster east nc durham 104 -l eastus &
create-cluster east nc durham 105 -l eastus &
create-cluster east nc east 101 -l eastus &
create-cluster east nc east 102 -l eastus &
create-cluster east nc east 103 -l eastus &
create-cluster east nc east 104 -l eastus &
create-cluster east nc east 105 -l eastus &
create-cluster east nc raleigh 101 -l eastus &
create-cluster east nc raleigh 102 -l eastus &
create-cluster east nc raleigh 103 -l eastus &
create-cluster east nc raleigh 104 -l eastus &
create-cluster east nc raleigh 105 -l eastus &
create-cluster east nc west 101 -l eastus &
create-cluster east nc west 102 -l eastus &
create-cluster east nc west 103 -l eastus &
create-cluster east nc west 104 -l eastus &
create-cluster east nc west 105 -l eastus &
create-cluster west ca la 101 -l westus &
create-cluster west ca la 102 -l westus &
create-cluster west ca la 103 -l westus &
create-cluster west ca la 104 -l westus &
create-cluster west ca la 105 -l westus &
create-cluster west ca north 101 -l westus &
create-cluster west ca north 102 -l westus &
create-cluster west ca north 103 -l westus &
create-cluster west ca north 104 -l westus &
create-cluster west ca north 105 -l westus &
create-cluster west ca sac 101 -l westus &
create-cluster west ca sac 102 -l westus &
create-cluster west ca sac 103 -l westus &
create-cluster west ca sac 104 -l westus &
create-cluster west ca sac 105 -l westus &
create-cluster west ca sand 101 -l westus &
create-cluster west ca sand 102 -l westus &
create-cluster west ca sand 103 -l westus &
create-cluster west ca sand 104 -l westus &
create-cluster west ca sand 105 -l westus &
create-cluster west ca sfo 101 -l westus &
create-cluster west ca sfo 102 -l westus &
create-cluster west ca sfo 103 -l westus &
create-cluster west ca sfo 104 -l westus &
create-cluster west ca sfo 105 -l westus &
create-cluster west ca south 101 -l westus &
create-cluster west ca south 102 -l westus &
create-cluster west ca south 103 -l westus &
create-cluster west ca south 104 -l westus &
create-cluster west ca south 105 -l westus &
create-cluster west ca west 101 -l westus &
create-cluster west ca west 102 -l westus &
create-cluster west ca west 103 -l westus &
create-cluster west ca west 104 -l westus &
create-cluster west ca west 105 -l westus &
create-cluster west wa central 101 -l westus &
create-cluster west wa central 102 -l westus &
create-cluster west wa central 103 -l westus &
create-cluster west wa central 104 -l westus &
create-cluster west wa central 105 -l westus &
create-cluster west wa east 101 -l westus &
create-cluster west wa east 102 -l westus &
create-cluster west wa east 103 -l westus &
create-cluster west wa east 104 -l westus &
create-cluster west wa east 105 -l westus &
create-cluster west wa olympia 101 -l westus &
create-cluster west wa olympia 102 -l westus &
create-cluster west wa olympia 103 -l westus &
create-cluster west wa olympia 104 -l westus &
create-cluster west wa olympia 105 -l westus &
create-cluster west wa sea 101 -l westus &
create-cluster west wa sea 102 -l westus &
create-cluster west wa sea 103 -l westus &
create-cluster west wa sea 104 -l westus &
create-cluster west wa sea 105 -l westus &
create-cluster west wa spokane 101 -l westus &
create-cluster west wa spokane 102 -l westus &
create-cluster west wa spokane 103 -l westus &
create-cluster west wa spokane 104 -l westus &
create-cluster west wa spokane 105 -l westus &
create-cluster west wa tacoma 101 -l westus &
create-cluster west wa tacoma 102 -l westus &
create-cluster west wa tacoma 103 -l westus &
create-cluster west wa tacoma 104 -l westus &
create-cluster west wa tacoma 105 -l westus &
create-cluster west wa west 101 -l westus &
create-cluster west wa west 102 -l westus &
create-cluster west wa west 103 -l westus &
create-cluster west wa west 104 -l westus &
create-cluster west wa west 105 -l westus &
