#!/bin/bash

# change to this directory
cd "$(dirname "${BASH_SOURCE[0]}")" || exit

create-cluster central ks kc 101 -l centralus &
create-cluster central ks kc 102 -l centralus &
create-cluster central ks kc 103 -l centralus &
create-cluster central ks kc 104 -l centralus &
create-cluster central ks kc 105 -l centralus &
create-cluster central ks wichita 101 -l centralus &
create-cluster central ks wichita 102 -l centralus &
create-cluster central ks wichita 103 -l centralus &
create-cluster central ks wichita 104 -l centralus &
create-cluster central ks wichita 105 -l centralus &
create-cluster central mo columbia 101 -l centralus &
create-cluster central mo columbia 102 -l centralus &
create-cluster central mo columbia 103 -l centralus &
create-cluster central mo columbia 104 -l centralus &
create-cluster central mo columbia 105 -l centralus &
create-cluster central mo east 101 -l centralus &
create-cluster central mo east 102 -l centralus &
create-cluster central mo east 103 -l centralus &
create-cluster central mo east 104 -l centralus &
create-cluster central mo east 105 -l centralus &
create-cluster central mo north 101 -l centralus &
create-cluster central mo north 102 -l centralus &
create-cluster central mo north 103 -l centralus &
create-cluster central mo north 104 -l centralus &
create-cluster central mo north 105 -l centralus &
create-cluster central mo south 101 -l centralus &
create-cluster central mo south 102 -l centralus &
create-cluster central mo south 103 -l centralus &
create-cluster central mo south 104 -l centralus &
create-cluster central mo south 105 -l centralus &
create-cluster central mo stlouis 101 -l centralus &
create-cluster central mo stlouis 102 -l centralus &
create-cluster central mo stlouis 103 -l centralus &
create-cluster central mo stlouis 104 -l centralus &
create-cluster central mo stlouis 105 -l centralus &
create-cluster central mo west 101 -l centralus &
create-cluster central mo west 102 -l centralus &
create-cluster central mo west 103 -l centralus &
create-cluster central mo west 104 -l centralus &
create-cluster central mo west 105 -l centralus &
create-cluster central tx aus 101 -l centralus &
create-cluster central tx aus 102 -l centralus &
create-cluster central tx aus 103 -l centralus &
create-cluster central tx aus 104 -l centralus &
create-cluster central tx aus 105 -l centralus &
create-cluster central tx dallas 101 -l centralus &
create-cluster central tx dallas 102 -l centralus &
create-cluster central tx dallas 103 -l centralus &
create-cluster central tx dallas 104 -l centralus &
create-cluster central tx dallas 105 -l centralus &
create-cluster central tx east 101 -l centralus &
create-cluster central tx east 102 -l centralus &
create-cluster central tx east 103 -l centralus &
create-cluster central tx east 104 -l centralus &
create-cluster central tx east 105 -l centralus &
create-cluster central tx houston 101 -l centralus &
create-cluster central tx houston 102 -l centralus &
create-cluster central tx houston 103 -l centralus &
create-cluster central tx houston 104 -l centralus &
create-cluster central tx houston 105 -l centralus &
create-cluster central tx north 101 -l centralus &
create-cluster central tx north 102 -l centralus &
create-cluster central tx north 103 -l centralus &
create-cluster central tx north 104 -l centralus &
create-cluster central tx north 105 -l centralus &
create-cluster central tx san 101 -l centralus &
create-cluster central tx san 102 -l centralus &
create-cluster central tx san 103 -l centralus &
create-cluster central tx san 104 -l centralus &
create-cluster central tx san 105 -l centralus &
create-cluster central tx south 101 -l centralus &
create-cluster central tx south 102 -l centralus &
create-cluster central tx south 103 -l centralus &
create-cluster central tx south 104 -l centralus &
create-cluster central tx south 105 -l centralus &
create-cluster central tx west 101 -l centralus &
create-cluster central tx west 102 -l centralus &
create-cluster central tx west 103 -l centralus &
create-cluster central tx west 104 -l centralus &
create-cluster central tx west 105 -l centralus &
create-cluster east ga athens 101 -l eastus &
create-cluster east ga athens 102 -l eastus &
create-cluster east ga athens 103 -l eastus &
create-cluster east ga athens 104 -l eastus &
create-cluster east ga athens 105 -l eastus &
create-cluster east ga atl 101 -l eastus &
create-cluster east ga atl 102 -l eastus &
create-cluster east ga atl 103 -l eastus &
create-cluster east ga atl 104 -l eastus &
create-cluster east ga atl 105 -l eastus &
create-cluster east ga north 101 -l eastus &
create-cluster east ga north 102 -l eastus &
create-cluster east ga north 103 -l eastus &
create-cluster east ga north 104 -l eastus &
create-cluster east ga north 105 -l eastus &
create-cluster east ga south 101 -l eastus &
create-cluster east ga south 102 -l eastus &
create-cluster east ga south 103 -l eastus &
create-cluster east ga south 104 -l eastus &
create-cluster east ga south 105 -l eastus &
