#!/bin/bash

# name: clean
# short: Remove the apps from the local k3d cluster

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

kubectl delete pod ngsa --ignore-not-found=true
kubectl delete pod webv --ignore-not-found=true
kubectl delete pod jumpbox --ignore-not-found=true

kubectl delete svc ngsa --ignore-not-found=true
kubectl delete svc webv --ignore-not-found=true

kubectl delete ns ngsa --ignore-not-found=true
kubectl delete ns monitoring --ignore-not-found=true
kubectl delete ns logging --ignore-not-found=true
