apiVersion: k3d.io/v1alpha2
kind: Simple
servers: 1
network: k3d
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"
volumes:
  - volume: /prometheus:/prometheus
    nodeFilters:
      - server[0]
ports:
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 80:80
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraServerArgs:
      - --tls-san=127.0.0.1
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true

registries:
  create:
    name: acrretailedge
  config: |
    mirrors:
      "acrretailedge.azurecr.io":
        endpoint:
          - https://acrretailedge.azurecr.io
    configs:
      "acrretailedge.azurecr.io":
        auth:
          username: acrretailedge
          password: xmw6zngF45aEiAs=fPjQBGgafHADB344
