#!/bin/bash

#name: heartbeat
#short: Check heartbeat status on the local cluster

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

if [ "$AKDC_SSL" = "" ]
then
    http http://"$AKDC_FQDN/heartbeat/17"
else
    http https://"$AKDC_FQDN/heartbeat/17"
fi
