apiVersion: apps/v1
kind: Deployment
metadata:
  name: webv-aioa
  namespace: ai-order-accuracy
  labels:
    app.kubernetes.io/name: webv-aioa
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: webv-aioa
  template:
    metadata:
      labels:
        app: webv-aioa
    spec:
      containers:
        - name: app
          image: ghcr.io/cse-labs/webv-red:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          args:
          - --sleep
          - "100"
          - --prometheus
          - --run-loop
          - --verbose
          - --log-format
          - Json
          - --server
          - http://ai-order-accuracy:8080
          - --files
          - benchmark.json
          - --zone
          - dev
          - --region
          - dev

---
apiVersion: v1
kind: Service
metadata:
  name: webv-aioa
  namespace: ai-order-accuracy
  labels:
    app: webv-aioa
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      nodePort: 30088
      protocol: TCP
      name: http
  selector:
    app: webv-aioa
